export { Home } from './Home';
export { About } from './About';
export { Committee } from './Committee';
export { Contact } from './Contact';
export { Events } from './Events';
export { Gallery } from './Gallery';
export { Welfare } from './Welfare';
export { ScholarshipFormPage } from './ScholarshipFormPage';
export { MeritListPage } from './MeritListPage';
export { default as APIExample } from './APIExample';
