export { Home } from './Home';
export { About } from './About';
export { Committee } from './Committee';
export { Contact } from './Contact';
export { Events } from './Events';
export { Patrons } from './Patrons';
export { Gallery } from './Gallery';
export { Publications } from './Publications';
export { Welfare } from './Welfare';
export { default as APIExample } from './APIExample';
